### ISSUE TITLE
Issue building project

### ISSUE THREAD

**Issue by TouficE** [inkline/inkline.io#1]
* **I'm submitting a:**
    - [x] Bug Report
  
* **Steps to reproduce** 
npx pnpm i --store=node_modules/.pnpm-store
npx pnpm run build

* **What is the expected behavior?** 
  Build successfully.

* **What is the current behavior?**
* 
C:\Users\Red\Downloads\inkline.io-main\node_modules\.pnpm\@inkline+inkline@3.0.0-rc.3_vue@3.2.26\node_modules\@inkline\inkline\mixins\index.js:1
export * from './computed';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:991:16)
    at Module._compile (internal/modules/cjs/loader.js:1039:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
    at Module.load (internal/modules/cjs/loader.js:940:32)
    at Function.Module._load (internal/modules/cjs/loader.js:781:14)
    at Module.require (internal/modules/cjs/loader.js:964:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Module.<anonymous> (C:\Users\Red\Downloads\inkline.io-main\.vite-ssg-temp\main.js:29:14)
    at Module._compile (internal/modules/cjs/loader.js:1075:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1096:10)
 ELIFECYCLE  Command failed with exit code 1.

**Comment by alexgrozav** [comment]
Hey @TouficE, I'm aware of the issue and working on a fix for it. I'll leave a message here when the new version is up.

Thank you! :)

**Comment by TouficE** [comment]
Hey @alexgrozav, I got it to compile by removing the vite-ssg in the build command and adding vite.   I was looking around noticed one user note that this could be due to the inkline dependency having module set to ESNEXT in tsconfig and the website project has module set to CommonJS. 

Kudos on the amazing work you have done with inkline.

**Comment by alexgrozav** [comment]
Hey, @TouficE! If you're still interested in building the docs, it now works as expected with proper SSG. Cheers! :) 

Thank you for the kind words. ❤️
